name: 'Get GitHub App Installation Token'
description: 'Get an installation access token from a GitHub App JWT token'
inputs:
  jwt-token:
    description: 'JWT token for GitHub App authentication'
    required: true
  installation-id:
    description: 'GitHub App installation ID'
    required: true
outputs:
  token:
    description: 'Installation access token'
  expires-at:
    description: 'Token expiration timestamp'
runs:
  using: 'composite'
  steps:
    - name: Get installation access token
      shell: bash
      run: |
        # Install required tools
        if ! command -v jq &> /dev/null; then
          sudo apt-get update && sudo apt-get install -y jq curl
        fi
        
        JWT_TOKEN="${{ inputs.jwt-token }}"
        INSTALLATION_ID="${{ inputs.installation-id }}"
        
        # Debug: Check if JWT token is set
        if [ -z "$JWT_TOKEN" ]; then
          echo "::error::JWT_TOKEN is empty or not set"
          echo "This means the JWT token from the previous step was not passed correctly"
          exit 1
        fi
        
        # Clean the JWT token (remove any whitespace/newlines that might have been added)
        JWT_TOKEN=$(echo -n "$JWT_TOKEN" | tr -d '\n\r\t ')
        
        # Debug: Show token info (masked)
        echo "JWT Token length: ${#JWT_TOKEN} characters"
        echo "JWT Token (first 50 chars): ${JWT_TOKEN:0:50}..."
        echo "JWT Token (last 10 chars): ...${JWT_TOKEN: -10}"
        echo "::add-mask::$JWT_TOKEN"
        
        # Verify token format (should be three parts separated by dots)
        TOKEN_PARTS=$(echo "$JWT_TOKEN" | tr -cd '.' | wc -c)
        if [ "$TOKEN_PARTS" -ne 2 ]; then
          echo "::error::JWT token format is incorrect (expected 3 parts separated by dots, found $((TOKEN_PARTS + 1)) parts)"
          echo "Token might be corrupted during transfer between actions"
          exit 1
        fi
        
        # Get installation access token using JWT
        API_URL="https://api.github.com/app/installations/$INSTALLATION_ID/access_tokens"
        
        echo "Requesting installation access token..."
        echo "  Installation ID: $INSTALLATION_ID"
        echo "  API Endpoint: $API_URL"
        
        RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
          -H "Authorization: Bearer $JWT_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "$API_URL")
        
        HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
        RESPONSE_BODY=$(echo "$RESPONSE" | sed '$d')
        
        if [ "$HTTP_CODE" != "201" ]; then
          echo "::error::Failed to generate installation token (HTTP $HTTP_CODE)"
          echo ""
          echo "Response body:"
          if command -v jq &> /dev/null; then
            echo "$RESPONSE_BODY" | jq '.' 2>/dev/null || echo "$RESPONSE_BODY"
          else
            echo "$RESPONSE_BODY"
          fi
          
          # Try to extract error message
          if command -v jq &> /dev/null; then
            ERROR_MSG=$(echo "$RESPONSE_BODY" | jq -r '.message // .error // empty' 2>/dev/null)
            if [ -n "$ERROR_MSG" ] && [ "$ERROR_MSG" != "null" ]; then
              echo ""
              echo "Error message: $ERROR_MSG"
              
              case "$ERROR_MSG" in
                "Bad credentials")
                  echo ""
                  echo "💡 Possible causes:"
                  echo "   - JWT token is invalid or expired"
                  echo "   - JWT token was corrupted during transfer between actions"
                  echo "   - App ID is incorrect"
                  echo "   - Private key doesn't match the App"
                  echo ""
                  echo "Debug info:"
                  echo "   JWT Token length: ${#JWT_TOKEN}"
                  echo "   Installation ID: $INSTALLATION_ID"
                  ;;
                "Not Found")
                  echo ""
                  echo "💡 Possible causes:"
                  echo "   - Installation ID is incorrect"
                  echo "   - GitHub App is not installed"
                  ;;
              esac
            fi
          fi
          exit 1
        fi
        
        # Parse JSON response
        TOKEN=$(echo "$RESPONSE_BODY" | jq -r '.token // empty')
        EXPIRES_AT=$(echo "$RESPONSE_BODY" | jq -r '.expires_at // empty')
        
        if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
          echo "::error::Token not found in response"
          echo "Response: $RESPONSE_BODY"
          exit 1
        fi
        
        # Save to outputs
        {
          echo "token<<EOF"
          echo "$TOKEN"
          echo "EOF"
        } >> $GITHUB_OUTPUT
        
        if [ -n "$EXPIRES_AT" ] && [ "$EXPIRES_AT" != "null" ]; then
          echo "expires-at=$EXPIRES_AT" >> $GITHUB_OUTPUT
        fi
        
        echo "::add-mask::$TOKEN"
        echo "✅ Successfully generated installation access token"
        if [ -n "$EXPIRES_AT" ] && [ "$EXPIRES_AT" != "null" ]; then
          echo "Token expires at: $EXPIRES_AT"
        fi

