name: 'Get GitHub App Installation Token'
description: 'Get an installation access token from a GitHub App JWT token'
inputs:
  jwt-token:
    description: 'JWT token for GitHub App authentication'
    required: true
  installation-id:
    description: 'GitHub App installation ID'
    required: true
outputs:
  token:
    description: 'Installation access token'
  expires-at:
    description: 'Token expiration timestamp'
runs:
  using: 'composite'
  steps:
    - name: Get installation access token
      shell: bash
      run: |
        # Install required tools
        if ! command -v jq &> /dev/null; then
          sudo apt-get update && sudo apt-get install -y jq curl
        fi
        
        JWT_TOKEN="${{ inputs.jwt-token }}"
        INSTALLATION_ID="${{ inputs.installation-id }}"
        
        # Clean the JWT token (remove any whitespace)
        JWT_TOKEN=$(echo -n "$JWT_TOKEN" | tr -d '\n\r\t ')
        
        # Get installation access token using JWT
        API_URL="https://api.github.com/app/installations/$INSTALLATION_ID/access_tokens"
        
        RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
          -H "Authorization: Bearer $JWT_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "$API_URL")
        
        HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
        RESPONSE_BODY=$(echo "$RESPONSE" | sed '$d')
        
        if [ "$HTTP_CODE" != "201" ]; then
          echo "::error::Failed to generate installation token (HTTP $HTTP_CODE)"
          echo "Response: $RESPONSE_BODY"
          exit 1
        fi
        
        # Parse JSON response
        TOKEN=$(echo "$RESPONSE_BODY" | jq -r '.token // empty')
        EXPIRES_AT=$(echo "$RESPONSE_BODY" | jq -r '.expires_at // empty')
        
        if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
          echo "::error::Token not found in response"
          echo "Response: $RESPONSE_BODY"
          exit 1
        fi
        
        # Save to outputs
        {
          echo "token<<EOF"
          echo "$TOKEN"
          echo "EOF"
        } >> $GITHUB_OUTPUT
        
        if [ -n "$EXPIRES_AT" ] && [ "$EXPIRES_AT" != "null" ]; then
          echo "expires-at=$EXPIRES_AT" >> $GITHUB_OUTPUT
        fi
        
        echo "::add-mask::$TOKEN"
        echo "✅ Successfully generated installation access token"
        if [ -n "$EXPIRES_AT" ] && [ "$EXPIRES_AT" != "null" ]; then
          echo "Token expires at: $EXPIRES_AT"
        fi

